// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (sql.Result, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (sql.Result, error)
	CreateEntries(ctx context.Context, arg CreateEntriesParams) (sql.Result, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (sql.Result, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteAccount(ctx context.Context, id int64) (sql.Result, error)
	DeleteEntries(ctx context.Context, id int64) (sql.Result, error)
	DeleteTransfer(ctx context.Context, id int64) (sql.Result, error)
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntries(ctx context.Context, id int64) (Entry, error)
	GetIdEntries(ctx context.Context) (Entry, error)
	GetLastInsertId(ctx context.Context) (int64, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccount(ctx context.Context, arg ListAccountParams) ([]Account, error)
	ListEntries(ctx context.Context) ([]Entry, error)
	ListTransfer(ctx context.Context) ([]Transfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (sql.Result, error)
	UpdateEntries(ctx context.Context, arg UpdateEntriesParams) (sql.Result, error)
	UpdateTransfer(ctx context.Context, arg UpdateTransferParams) (sql.Result, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error)
	UserExist(ctx context.Context, username string) (bool, error)
	UserMoreThanOne(ctx context.Context, username string) (int64, error)
}

var _ Querier = (*Queries)(nil)
