name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      mysql: 
        image: mysql:latest
        env:
          MYSQL_PASSWORD: secret
          MYSQL_USERNAME: root
          MYSQL_DATABSE: simple_bank

    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install golang-migrate
      run: 
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate.linux-amd46 /usr/bin/migrate
        which migrate

    - name: Install golang-migrate
      run: migrate -path db/migration -database "mysql://root:secret@tcp(localhost:3307)/simple_bank" -verbose up  

    - name: Test
      run: go test -v -cover ./...
